do $$
declare
  v_employer_id uuid;
begin
  select id
  into v_employer_id
  from public.profiles
  where role = 'employer'
  order by created_at desc
  limit 1;

  if v_employer_id is null then
    raise exception 'No employer profile found. Please sign up as an employer first.';
  end if;

  insert into public.jobs (
    employer_id,
    title,
    description,
    required_education,
    required_skills,
    required_experience,
    work_mode,
    location,
    job_type,
    salary_min,
    salary_max
  )
  values
    (
      v_employer_id,
      'Marketing Coordinator',
      'Support campaign planning, social media scheduling, email marketing, and event promotion. The role suits a detail-oriented communicator who can coordinate timelines and prepare campaign reports.',
      'Bachelor',
      array['Marketing', 'Social Media', 'Communication', 'Content Writing', 'Campaign Planning'],
      1,
      'Hybrid',
      'Sydney',
      'Full-time',
      60000,
      78000
    ),
    (
      v_employer_id,
      'Retail Store Supervisor',
      'Lead daily store operations, support sales staff, manage stock presentation, handle customer concerns, and help achieve weekly sales targets.',
      'Diploma',
      array['Customer Service', 'Retail Sales', 'Team Leadership', 'Stock Management', 'Problem Solving'],
      2,
      'On-site',
      'Melbourne',
      'Full-time',
      58000,
      72000
    ),
    (
      v_employer_id,
      'Administrative Assistant',
      'Provide office support including calendar management, document preparation, data entry, phone enquiries, and coordination of internal meetings.',
      'High School',
      array['Administration', 'Data Entry', 'Microsoft Office', 'Scheduling', 'Communication'],
      1,
      'On-site',
      'Wollongong',
      'Full-time',
      50000,
      62000
    ),
    (
      v_employer_id,
      'Human Resources Officer',
      'Assist with recruitment, onboarding, employee records, policy communication, and HR reporting. The role requires confidentiality and strong interpersonal skills.',
      'Bachelor',
      array['Human Resources', 'Recruitment', 'Onboarding', 'Employee Relations', 'Documentation'],
      2,
      'Hybrid',
      'Sydney',
      'Full-time',
      68000,
      88000
    ),
    (
      v_employer_id,
      'Primary School Teaching Assistant',
      'Support classroom learning, prepare materials, assist students with activities, and help teachers maintain a positive learning environment.',
      'Diploma',
      array['Education Support', 'Child Development', 'Classroom Support', 'Patience', 'Communication'],
      0,
      'On-site',
      'Newcastle',
      'Part-time',
      42000,
      56000
    ),
    (
      v_employer_id,
      'Early Childhood Educator',
      'Plan and support age-appropriate learning activities, maintain child safety, communicate with families, and document learning progress.',
      'Diploma',
      array['Early Childhood Education', 'Child Safety', 'Learning Activities', 'Family Communication', 'Observation'],
      1,
      'On-site',
      'Brisbane',
      'Full-time',
      52000,
      68000
    ),
    (
      v_employer_id,
      'Registered Nurse',
      'Provide patient care, monitor health conditions, administer medication, maintain clinical documentation, and collaborate with healthcare teams.',
      'Bachelor',
      array['Nursing', 'Patient Care', 'Clinical Documentation', 'Medication Administration', 'Teamwork'],
      2,
      'On-site',
      'Perth',
      'Full-time',
      76000,
      98000
    ),
    (
      v_employer_id,
      'Medical Receptionist',
      'Manage patient bookings, answer phone enquiries, process forms, update patient records, and support doctors with clinic administration.',
      'High School',
      array['Reception', 'Patient Service', 'Appointment Scheduling', 'Data Entry', 'Confidentiality'],
      1,
      'On-site',
      'Adelaide',
      'Part-time',
      45000,
      58000
    ),
    (
      v_employer_id,
      'Dental Assistant',
      'Prepare treatment rooms, assist dentists during procedures, sterilise instruments, update patient records, and provide friendly patient support.',
      'Certificate',
      array['Dental Assisting', 'Sterilisation', 'Patient Care', 'Clinical Support', 'Organisation'],
      0,
      'On-site',
      'Sydney',
      'Full-time',
      48000,
      62000
    ),
    (
      v_employer_id,
      'Disability Support Worker',
      'Support clients with daily living activities, community access, personal goals, and care documentation while maintaining dignity and safety.',
      'Certificate',
      array['Disability Support', 'Personal Care', 'Community Access', 'Care Notes', 'Empathy'],
      1,
      'On-site',
      'Canberra',
      'Part-time',
      52000,
      68000
    ),
    (
      v_employer_id,
      'Accountant',
      'Prepare financial reports, reconcile accounts, assist with budgets, process tax documentation, and support month-end reporting.',
      'Bachelor',
      array['Accounting', 'Financial Reporting', 'Reconciliation', 'Excel', 'Budgeting'],
      2,
      'Hybrid',
      'Melbourne',
      'Full-time',
      72000,
      95000
    ),
    (
      v_employer_id,
      'Bookkeeper',
      'Maintain financial records, process invoices, reconcile bank transactions, manage payroll entries, and prepare basic reports for management.',
      'Certificate',
      array['Bookkeeping', 'Payroll', 'Invoicing', 'Bank Reconciliation', 'Xero'],
      1,
      'Remote',
      'Australia',
      'Part-time',
      50000,
      65000
    ),
    (
      v_employer_id,
      'Customer Service Representative',
      'Respond to customer enquiries by phone, email, and chat. Resolve common issues, update records, and escalate complex cases to specialists.',
      'High School',
      array['Customer Service', 'Communication', 'Problem Solving', 'CRM', 'Attention to Detail'],
      0,
      'Remote',
      'Australia',
      'Full-time',
      50000,
      62000
    ),
    (
      v_employer_id,
      'Sales Consultant',
      'Build customer relationships, explain product options, prepare quotes, follow up leads, and work toward monthly sales targets.',
      'High School',
      array['Sales', 'Negotiation', 'Customer Relationship', 'Product Knowledge', 'Communication'],
      1,
      'Hybrid',
      'Sydney',
      'Full-time',
      60000,
      90000
    ),
    (
      v_employer_id,
      'Real Estate Assistant',
      'Support property listings, open home preparation, client communication, document filing, and appointment coordination for a busy agency.',
      'High School',
      array['Real Estate', 'Administration', 'Client Communication', 'Scheduling', 'Attention to Detail'],
      1,
      'On-site',
      'Gold Coast',
      'Full-time',
      52000,
      68000
    ),
    (
      v_employer_id,
      'Graphic Designer',
      'Create digital and print assets for campaigns, social media, brochures, and presentations while maintaining brand consistency.',
      'Bachelor',
      array['Graphic Design', 'Adobe Creative Suite', 'Branding', 'Layout Design', 'Creativity'],
      1,
      'Hybrid',
      'Melbourne',
      'Contract',
      58000,
      82000
    ),
    (
      v_employer_id,
      'Content Writer',
      'Write articles, website copy, newsletters, and campaign content. Research topics, edit drafts, and adapt tone for different audiences.',
      'Bachelor',
      array['Content Writing', 'Editing', 'Research', 'SEO', 'Communication'],
      1,
      'Remote',
      'Australia',
      'Contract',
      55000,
      75000
    ),
    (
      v_employer_id,
      'Event Coordinator',
      'Coordinate suppliers, venues, schedules, guest communication, and event-day logistics for corporate and community events.',
      'Diploma',
      array['Event Planning', 'Supplier Coordination', 'Logistics', 'Budget Tracking', 'Communication'],
      2,
      'On-site',
      'Brisbane',
      'Full-time',
      62000,
      80000
    ),
    (
      v_employer_id,
      'Hotel Front Desk Agent',
      'Welcome guests, manage check-ins and check-outs, handle reservations, answer enquiries, and support a positive guest experience.',
      'High School',
      array['Hospitality', 'Guest Service', 'Reservations', 'Communication', 'Problem Solving'],
      0,
      'On-site',
      'Sydney',
      'Full-time',
      48000,
      60000
    ),
    (
      v_employer_id,
      'Chef de Partie',
      'Prepare high-quality dishes, manage a kitchen section, follow food safety standards, and support menu preparation during busy service periods.',
      'Certificate',
      array['Cooking', 'Food Safety', 'Kitchen Operations', 'Time Management', 'Teamwork'],
      3,
      'On-site',
      'Melbourne',
      'Full-time',
      62000,
      78000
    ),
    (
      v_employer_id,
      'Warehouse Coordinator',
      'Coordinate receiving, picking, packing, stock checks, dispatch documentation, and safe warehouse procedures.',
      'High School',
      array['Warehouse Operations', 'Inventory Control', 'Dispatch', 'Forklift', 'Safety'],
      1,
      'On-site',
      'Perth',
      'Full-time',
      56000,
      70000
    ),
    (
      v_employer_id,
      'Logistics Planner',
      'Plan deliveries, coordinate transport providers, monitor shipment status, solve scheduling issues, and maintain logistics records.',
      'Diploma',
      array['Logistics', 'Transport Planning', 'Scheduling', 'Problem Solving', 'Excel'],
      2,
      'Hybrid',
      'Adelaide',
      'Full-time',
      68000,
      88000
    ),
    (
      v_employer_id,
      'Construction Site Administrator',
      'Support site documentation, contractor records, purchase orders, safety paperwork, and communication between office and site teams.',
      'Diploma',
      array['Construction Administration', 'Document Control', 'Purchase Orders', 'Safety Records', 'Communication'],
      2,
      'On-site',
      'Canberra',
      'Full-time',
      65000,
      85000
    ),
    (
      v_employer_id,
      'Civil Engineering Graduate',
      'Assist engineers with site inspections, design documentation, project reports, and coordination for infrastructure projects.',
      'Bachelor',
      array['Civil Engineering', 'AutoCAD', 'Project Documentation', 'Site Inspection', 'Problem Solving'],
      0,
      'Hybrid',
      'Sydney',
      'Full-time',
      68000,
      82000
    ),
    (
      v_employer_id,
      'Environmental Officer',
      'Monitor environmental compliance, prepare reports, support sustainability initiatives, and assist with audits and site assessments.',
      'Bachelor',
      array['Environmental Science', 'Compliance', 'Sustainability', 'Reporting', 'Site Assessment'],
      1,
      'Hybrid',
      'Hobart',
      'Full-time',
      65000,
      85000
    ),
    (
      v_employer_id,
      'Legal Assistant',
      'Prepare legal documents, manage client files, schedule appointments, conduct basic research, and support solicitors with administration.',
      'Diploma',
      array['Legal Administration', 'Document Preparation', 'Research', 'Client Service', 'Confidentiality'],
      1,
      'On-site',
      'Sydney',
      'Full-time',
      58000,
      76000
    ),
    (
      v_employer_id,
      'Paralegal',
      'Assist with case preparation, legal research, drafting correspondence, file management, and court document organisation.',
      'Bachelor',
      array['Legal Research', 'Case Preparation', 'Drafting', 'File Management', 'Attention to Detail'],
      2,
      'Hybrid',
      'Melbourne',
      'Full-time',
      70000,
      92000
    ),
    (
      v_employer_id,
      'Research Assistant',
      'Support research projects by collecting data, reviewing literature, preparing summaries, and maintaining accurate project records.',
      'Bachelor',
      array['Research', 'Data Collection', 'Literature Review', 'Writing', 'Analysis'],
      0,
      'Hybrid',
      'Wollongong',
      'Part-time',
      48000,
      65000
    ),
    (
      v_employer_id,
      'Personal Trainer',
      'Create training programs, coach clients, track progress, maintain safety standards, and support member engagement in a fitness centre.',
      'Certificate',
      array['Fitness Training', 'Coaching', 'Program Design', 'Customer Service', 'Motivation'],
      1,
      'On-site',
      'Brisbane',
      'Part-time',
      45000,
      70000
    ),
    (
      v_employer_id,
      'Operations Coordinator',
      'Coordinate daily operations, monitor task progress, update process documentation, support reporting, and communicate with internal teams.',
      'Diploma',
      array['Operations', 'Process Improvement', 'Reporting', 'Coordination', 'Communication'],
      2,
      'Hybrid',
      'Sydney',
      'Full-time',
      68000,
      88000
    );
end $$;
